In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2


In [2]:
n, d = 10, 5

In [7]:
a = np.random.randn(n, d)
print(a)

[[ 5.63515846e-01  1.91474010e-01  1.51893464e+00  1.05601712e+00
   1.65844478e+00]
 [ 4.25974871e-01  1.40640862e+00 -8.74026153e-02  1.01691173e-01
  -1.52511400e+00]
 [-1.86410612e-01  1.24247993e-01  1.68463877e-01  3.20317076e+00
   2.81717433e-01]
 [-2.09504676e-01 -7.16236165e-01 -1.38073241e+00 -1.56612153e+00
  -2.49507902e-01]
 [ 8.33134752e-01  1.65844655e-01  1.62956505e-01 -1.78016581e-01
   1.15778593e+00]
 [-9.79773996e-01  5.65679656e-01  6.17553199e-01 -1.90515291e-01
  -6.21602464e-01]
 [-1.66335319e-01  6.38547338e-01 -1.78033023e-01 -1.01058753e-01
   4.14712466e-01]
 [-1.15126422e+00  7.48881501e-01 -5.68474923e-01 -1.62846538e+00
   5.62946901e-01]
 [ 2.10878342e-03  6.12328781e-01  1.29498218e+00 -6.95349426e-01
   6.85146967e-01]
 [-2.66348972e+00 -3.23676409e-01 -1.55491619e+00  8.08047783e-03
   1.08882351e+00]]


In [8]:
a = (a - np.mean(a, axis=0)) / np.std(a, axis=0)


[[ 0.94394741 -0.26604309  1.59235164  0.80796476  1.47772064]
 [ 0.80232139  1.89057294 -0.09088817  0.07715172 -2.10492864]
 [ 0.17174769 -0.3853752   0.1772278   2.45223305 -0.07159306]
 [ 0.14796772 -1.87730867 -1.44613545 -1.20004217 -0.66941273]
 [ 1.22157416 -0.31153745  0.17145676 -0.13704561  0.91429926]
 [-0.64517906  0.39820492  0.64781704 -0.146617   -1.08815302]
 [ 0.19241924  0.52755148 -0.18585746 -0.0781121   0.07807421]
 [-0.82176264  0.72340434 -0.59499156 -1.24778446  0.24489129]
 [ 0.36586623  0.48101123  1.35767757 -0.53321381  0.38241034]
 [-2.37890214 -1.1804805  -1.62865818  0.00546561  0.83669172]]


In [10]:
# After this processing, each dimension has zero mean and unit variance
print(a, "\n\n", np.mean(a, axis=0), "\n\n", np.std(a, axis=0))

[[ 0.94394741 -0.26604309  1.59235164  0.80796476  1.47772064]
 [ 0.80232139  1.89057294 -0.09088817  0.07715172 -2.10492864]
 [ 0.17174769 -0.3853752   0.1772278   2.45223305 -0.07159306]
 [ 0.14796772 -1.87730867 -1.44613545 -1.20004217 -0.66941273]
 [ 1.22157416 -0.31153745  0.17145676 -0.13704561  0.91429926]
 [-0.64517906  0.39820492  0.64781704 -0.146617   -1.08815302]
 [ 0.19241924  0.52755148 -0.18585746 -0.0781121   0.07807421]
 [-0.82176264  0.72340434 -0.59499156 -1.24778446  0.24489129]
 [ 0.36586623  0.48101123  1.35767757 -0.53321381  0.38241034]
 [-2.37890214 -1.1804805  -1.62865818  0.00546561  0.83669172]] 

 [ 4.44089210e-17 -2.22044605e-17  0.00000000e+00 -4.31946146e-17
 -6.66133815e-17] 

 [1. 1. 1. 1. 1.]
